#!/bin/bash
# Launches an instance of polybar

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

# Detect primary display; credits: https://github.com/polybar/polybar/issues/763
if type "xrandr"; then
	  for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
		      MONITOR=$m polybar --reload bar &
		        done
		else
			  polybar --reload bar &
fi

# Launch Polybar, using default config location ~/.config/polybar/config
polybar bar &

echo "Polybar launched..."
