#! /bin/sh

#### AUTOSTART ####
sxhkd &
picom --experimental-backends &
synclient TapButton1=1 TapButton2=3 TapButton3=2 & #For laptop touchpad
nm-applet &
polybar mybar &
feh --bg-fill ~/Bilder/wallpaper.jpg &
xset -b & #For annoying beeping sound
start-pulseaudio-x11 &

#### WORKSPACES AND BORDERS ####

bspc monitor eDP-1  -d I II III IV V
bspc monitor DP-2-3 -d VI VII

bspc config border_width         0
bspc config window_gap           4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Spotify desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#Focus on pointer
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
